name: Build APK and Backend JAR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # IMPORTANT FIX
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build Backend JAR
      - name: Build Backend JAR
        run: ./gradlew :backend:build

      # Build Android APK
      - name: Build APK
        run: ./gradlew :android-app:assembleDebug

      # Upload JAR
      - name: Upload Backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: Backend-JAR
          path: backend/build/libs/*.jar

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: android-app/build/outputs/apk/debug/*.apk
